# Generated by Django 2.0.7 on 2019-01-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_1',
            field=models.CharField(default='asdasd', max_length=60),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_2',
            field=models.CharField(default='asdasd', max_length=60),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_3',
            field=models.CharField(default='asdasd', max_length=60),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_4',
            field=models.CharField(default='asdasd', max_length=60),
        ),
    ]
