# Generated by Django 2.0.7 on 2019-01-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='question_1',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='question_10',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='result',
            name='question_2',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='question_3',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='result',
            name='question_4',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='result',
            name='question_5',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='result',
            name='question_6',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='result',
            name='question_7',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='result',
            name='question_8',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='result',
            name='question_9',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
